Refactor/auth
Jason1258t/elegram pull request #2
Opened 2024-07-29 12:18 UTC by kharlamcik

2024-07-29 13:15 UTC, Jason1258t requested changes
Написал коментов по коду измененному, в паре мест поправить надо точно

2024-07-29 13:15 UTC, Jason1258t commented on lib/screen/auth/widget/phone.dart
> +        bottomSheetHeight: 700,
хуевато высоту константой такой большой задавать, а паддинг чисто покрасивее значение было б неплохо взять там 12 или 10, а то нестандартное и непонятное значение

2024-07-29 13:15 UTC, Jason1258t commented on lib/screen/auth/widget/phone.dart
> +                    validatePhoneNumber(context,
подожди у тебя две функции на валидцаию что-ли? одна тут в updateButtonState а вторя еще где-то?

2024-07-29 13:15 UTC, Jason1258t commented on lib/screen/auth/widget/validate_phone_number.dart
> +
я понял в чем отличие от того что было повешено в листенере, но тут ту мач немного функций для просто валидации, по сути тебе если и надо что-то показывать(и то обычно под филдом красненьким) то только ошибку, а то что он валидный будет понятно и на моменте загрузки ии перекидывали на другой экран как по мне. Тут даже не мой доеб а просто даже Single responsobility не проходит, потому что валидейт не только валидирует

2024-07-29 13:15 UTC, Jason1258t commented on lib/utils/colors.dart
>    static const buttonColor = Color(0xFF212F3F);
обычно у многих кнопок как раз стоит primary цвет, как минимум в активном состоянии, а для текстов бывают стили типо onBackground и так далее, не критично просто как инфа

2024-07-29 13:15 UTC, Jason1258t commented on pubspec.yaml
> +  country_icons: ^2.0.2
я их немного раскидываю где пакеты к ui где к логике и тд, так что тоже не пихай в пустые места просто

2024-07-31 13:46 UTC, kharlamcik commented on lib/screen/auth/widget/button_phone.dart
> +
А нахуя, Ink как контейнер, InkWell нажатие само

2024-07-31 13:49 UTC, kharlamcik commented on pubspec.yaml
> +  country_icons: ^2.0.2
а я не ебал

2024-07-31 16:37 UTC, Jason1258t commented on lib/screen/auth/widget/button_phone.dart
> +
ну я вот не ебу там еще контейнер был или типо того я как раз к этому и приедался

2024-08-01 09:57 UTC, kharlamcik commented on lib/screen/auth/widget/button_phone.dart
> +
А, всё увидел

2024-08-01 10:19 UTC, merged